### ISSUE TITLE
Correction for raw affiliation Neurchirurgie, Hotel-Dieu de France, Beyrouth, Liban

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#12]
Correction needed for raw affiliation Neurchirurgie, Hotel-Dieu de France, Beyrouth, Liban
raw_affiliation_name: Neurchirurgie, Hotel-Dieu de France, Beyrouth, Liban
new_rors: 04w1m5n60
previous_rors: 03jmjy508
works_examples: W4311983103

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
