### ISSUE TITLE
Correction for raw affiliation Hotel Dieu de France hospital, St Joseph University

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#14]
Correction needed for raw affiliation Hotel Dieu de France hospital, St Joseph University
raw_affiliation_name: Hotel Dieu de France hospital, St Joseph University
new_rors: 04w1m5n60
previous_rors: 03jmjy508
works_examples: W4319082805

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
