### ISSUE TITLE
Correction for raw affiliation Arènes, Sciences Po Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#16]
Correction needed for raw affiliation Arènes, Sciences Po Rennes
raw_affiliation_name: Arènes, Sciences Po Rennes
new_rors: 01fmctt82;00m4rxj18
previous_rors: 05fe7ax82
works_examples: W4205920303;W4205602457;W4205618948;W4206638148;W4205451072;W4206335064

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
