### ISSUE TITLE
Correction for raw affiliation ASM ‐ Archéologie des Sociétés Méditerranéennes, UMR 5140 Université Paul‐Valéry, CNRS, MCC Montpellier France

### ISSUE THREAD

**Issue by dataesri** [dataesr/openalex-affiliations#162]
Correction needed for raw affiliation ASM ‐ Archéologie des Sociétés Méditerranéennes, UMR 5140 Université Paul‐Valéry, CNRS, MCC Montpellier France
raw_affiliation_name: ASM ‐ Archéologie des Sociétés Méditerranéennes, UMR 5140 Université Paul‐Valéry, CNRS, MCC Montpellier France
new_rors: 02feahw73
previous_rors: 007xqmx73;02feahw73
works_examples: W4381308055
contact: f4cce70e04880d7a5c36f13e755719b6:1cc7c793eb747caa07461f00b64b @ unistra.fr

**Comment by HelloiseG** [comment]
Bonjour, j'ai créé un doublon d'issue  - erreur de manipulation lors du webinaire, désolée
Cette issue peut être supprimée
