### ISSUE TITLE
Correction for raw affiliation CNRS, Arènes/Sciences Po Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#17]
Correction needed for raw affiliation CNRS, Arènes/Sciences Po Rennes
raw_affiliation_name: CNRS, Arènes/Sciences Po Rennes
new_rors: 02feahw73;00m4rxj18;01fmctt82
previous_rors: 02feahw73;05fe7ax82
works_examples: W4206198627;W4205091610

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
