### ISSUE TITLE
Correction for raw affiliation Sciences Po Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#18]
Correction needed for raw affiliation Sciences Po Rennes
raw_affiliation_name: Sciences Po Rennes
new_rors: 01fmctt82
previous_rors: 05fe7ax82
works_examples: W4249153842

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
