### ISSUE TITLE
Correction for raw affiliation Société d’Histoire et d’Archéologie de la Lorraine, Pays de Bitche,  France

### ISSUE THREAD

**Issue by dataesri** [dataesr/openalex-affiliations#182]
Correction needed for raw affiliation Société d’Histoire et d’Archéologie de la Lorraine, Pays de Bitche,  France
raw_affiliation_name: Société d’Histoire et d’Archéologie de la Lorraine, Pays de Bitche,  France
new_rors: 
previous_rors: 007xqmx73
works_examples: W4387497897
contact: 75efc8a5f903c5fd9024bfb7c3f23bcb:769939bd65835c598d5303691ce7 @ unistra.fr

**Comment by HelloiseG** [comment]
Bonjour, j'ai créé un doublon d'issue  - erreur de manipulation lors du webinaire, désolée
Cette issue peut être supprimée
