### ISSUE TITLE
Correction for raw affiliation Sciences Po Rennes - Institut d'études politiques de Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#19]
Correction needed for raw affiliation Sciences Po Rennes - Institut d'études politiques de Rennes
raw_affiliation_name: Sciences Po Rennes - Institut d'études politiques de Rennes
new_rors: 01fmctt82
previous_rors: 05fe7ax82
works_examples: W3122389227;W4289887567

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
