### ISSUE TITLE
Correction for raw affiliation Professeur de science politique — Sciences Po Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#20]
Correction needed for raw affiliation Professeur de science politique — Sciences Po Rennes
raw_affiliation_name: Professeur de science politique — Sciences Po Rennes
new_rors: 01fmctt82
previous_rors: 05fe7ax82
works_examples: W3194941837

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
