### ISSUE TITLE
Correction for raw affiliation Sciences po Rennes (FR)

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#21]
Correction needed for raw affiliation Sciences po Rennes (FR)
raw_affiliation_name: Sciences po Rennes (FR)
new_rors: 01fmctt82
previous_rors: 05fe7ax82
works_examples: W3134094778;W3130132475

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
