### ISSUE TITLE
Correction for raw affiliation Institut d'Etudes Transtextuelles et Transculturelles; Sciences Po Rennes - Institut d'études politiques de Rennes; Équipes de Recherches Interlangues : Mémoires, Identités, Territoires

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#22]
Correction needed for raw affiliation Institut d'Etudes Transtextuelles et Transculturelles; Sciences Po Rennes - Institut d'études politiques de Rennes; Équipes de Recherches Interlangues : Mémoires, Identités, Territoires
raw_affiliation_name: Institut d'Etudes Transtextuelles et Transculturelles; Sciences Po Rennes - Institut d'études politiques de Rennes; Équipes de Recherches Interlangues : Mémoires, Identités, Territoires
new_rors: 01fmctt82
previous_rors: 05fe7ax82;026tc4g97
works_examples: W4389972357;W4389972377;W4390088609;W4390302731;W4390132712;W4390088597;W4390132710

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
