### ISSUE TITLE
Correction for raw affiliation Maîtresse de conférences HDR en droit privé, Sciences Po Rennes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#23]
Correction needed for raw affiliation Maîtresse de conférences HDR en droit privé, Sciences Po Rennes
raw_affiliation_name: Maîtresse de conférences HDR en droit privé, Sciences Po Rennes
new_rors: 01fmctt82
previous_rors: 05fe7ax82
works_examples: W4391240423

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
