### ISSUE TITLE
Correction for raw affiliation BRGM

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#24]
Correction needed for raw affiliation BRGM
raw_affiliation_name: BRGM
new_rors: 05hnb7x64
previous_rors: 
works_examples: W3109133484;W3137760966;W3125021631;W4233340296;W3119429303;W3099149780;W3135193675

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
