### ISSUE TITLE
Correction for raw affiliation BRGM - French geological survey

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#25]
Correction needed for raw affiliation BRGM - French geological survey
raw_affiliation_name: BRGM - French geological survey
new_rors: 05hnb7x64
previous_rors: 
works_examples: W3137760966;W3135193675

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
