### ISSUE TITLE
Correction for raw affiliation French Geological Survey (BRGM)

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#26]
Correction needed for raw affiliation French Geological Survey (BRGM)
raw_affiliation_name: French Geological Survey (BRGM)
new_rors: 05hnb7x64
previous_rors: 035a68863
works_examples: W3128468793

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
