### ISSUE TITLE
Correction for raw affiliation BRGM, 3Â av.Â C.Â Guillemin, 45060 OrlÃ©ans CEDEXÂ 2, France

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#27]
Correction needed for raw affiliation BRGM, 3Â av.Â C.Â Guillemin, 45060 OrlÃ©ans CEDEXÂ 2, France
raw_affiliation_name: BRGM, 3Â av.Â C.Â Guillemin, 45060 OrlÃ©ans CEDEXÂ 2, France
new_rors: 05hnb7x64
previous_rors: 
works_examples: W2995529867

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
