### ISSUE TITLE
Correction for raw affiliation BRGM, Direction de la Recherche

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#28]
Correction needed for raw affiliation BRGM, Direction de la Recherche
raw_affiliation_name: BRGM, Direction de la Recherche
new_rors: 05hnb7x64
previous_rors: 
works_examples: W3110222106

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
