### ISSUE TITLE
Correction for raw affiliation BRGM, Univ. Montpellier, Montpellier, France

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#29]
Correction needed for raw affiliation BRGM, Univ. Montpellier, Montpellier, France
raw_affiliation_name: BRGM, Univ. Montpellier, Montpellier, France
new_rors: 051escj72;05hnb7x64
previous_rors: 051escj72
works_examples: W3169911710;W4200035625

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
