### ISSUE TITLE
Correction for raw affiliation ESSEC Business School, Singapore, Singapore

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#3]
Correction needed for raw affiliation ESSEC Business School, Singapore, Singapore
raw_affiliation_name: ESSEC Business School, Singapore, Singapore
new_rors: 
previous_rors: 02hxmqn30
works_examples: W4389132380;W4389132376;W4389132308;W4389132399;W4389132840;W4389132364;W4389132400

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
