### ISSUE TITLE
Correction for raw affiliation UniversitÃ© dâOrlÃ©ans, CNRS, BRGM, Institut des Sciences de la Terre dâOrlÃ©ans (ISTO), 1A rue de la FÃ©rollerie, 45071 OrlÃ©ans Cedex 2 (France)

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#30]
Correction needed for raw affiliation UniversitÃ© dâOrlÃ©ans, CNRS, BRGM, Institut des Sciences de la Terre dâOrlÃ©ans (ISTO), 1A rue de la FÃ©rollerie, 45071 OrlÃ©ans Cedex 2 (France)
raw_affiliation_name: UniversitÃ© dâOrlÃ©ans, CNRS, BRGM, Institut des Sciences de la Terre dâOrlÃ©ans (ISTO), 1A rue de la FÃ©rollerie, 45071 OrlÃ©ans Cedex 2 (France)
new_rors: 05hnb7x64;01cf2sz15;02feahw73
previous_rors: 01cf2sz15;02feahw73
works_examples: W3196583509;W4200002541;W4200417460;W4200235869;W4200562545

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
