### ISSUE TITLE
Correction for raw affiliation BRGM - French Geological Survey

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#31]
Correction needed for raw affiliation BRGM - French Geological Survey
raw_affiliation_name: BRGM - French Geological Survey
new_rors: 05hnb7x64
previous_rors: 035a68863
works_examples: W3184163600;W3194641070;W4389767468

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
