### ISSUE TITLE
Correction for raw affiliation Univ. OrlÃ©ans, CNRS, BRGM, ISTO, UMR 7327, OrlÃ©ans, F-45071, France

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#32]
Correction needed for raw affiliation Univ. OrlÃ©ans, CNRS, BRGM, ISTO, UMR 7327, OrlÃ©ans, F-45071, France
raw_affiliation_name: Univ. OrlÃ©ans, CNRS, BRGM, ISTO, UMR 7327, OrlÃ©ans, F-45071, France
new_rors: 02feahw73;05hnb7x64
previous_rors: 02feahw73
works_examples: W4293441731;W4309173062

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
