### ISSUE TITLE
Correction for raw affiliation BRGM, F-45060 OrlÃ©ans, France

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#33]
Correction needed for raw affiliation BRGM, F-45060 OrlÃ©ans, France
raw_affiliation_name: BRGM, F-45060 OrlÃ©ans, France
new_rors: 05hnb7x64
previous_rors: 
works_examples: W4280520091;W4292939765;W4292939767;W4292939766;W4388761979

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
