### ISSUE TITLE
Correction for raw affiliation . BRGM -University of Montpellier, 1039 Rue de Pinville, 34000 Montpellier, France.

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#34]
Correction needed for raw affiliation . BRGM -University of Montpellier, 1039 Rue de Pinville, 34000 Montpellier, France.
raw_affiliation_name: . BRGM -University of Montpellier, 1039 Rue de Pinville, 34000 Montpellier, France.
new_rors: 051escj72;05hnb7x64
previous_rors: 051escj72
works_examples: W4317940077;W4320082213

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
