### ISSUE TITLE
Correction for raw affiliation Sciences Po Aix, Aix-en-Provence, France

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#4]
Correction needed for raw affiliation Sciences Po Aix, Aix-en-Provence, France
raw_affiliation_name: Sciences Po Aix, Aix-en-Provence, France
new_rors: 
previous_rors: 05fe7ax82
works_examples: W4323892946;W4323892949;W4323892472;W4323892943;W4323892419;W4323892778;W4323892412;W4323892965;W4323892216

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
