### ISSUE TITLE
Correction for raw affiliation L3S and TIB

### ISSUE THREAD

**Issue by dataesri** [dataesr/openalex-affiliations#4268]
Correction needed for raw affiliation L3S and TIB
raw_affiliation_name: L3S and TIB
new_rors: 0304hq317;04aj4c181
previous_rors: 
works_examples: W4393590113;W4393458274;W4393631527;W4393647884
contact: e9543653964b5ce67b4fbaaef0667646:b00cb674cadd42a031cf739342c7d078c983 @ tib.eu

**Comment by hauschke** [comment]
Correction:
new_rors: 039t4wk02;04aj4c181

**Comment by annelhote** [comment]
Hello @hauschke, as the issues will be consumed automatically, your comment won't be taken into consideration. If there is any error in the issue, the best would be to delete the issue and resubmit any correction into [Work-magnet](https://works-magnet.dataesr.ovh/). Thanks !

**Comment by annelhote** [comment]
Sorry, closing it is enough. I close it so you can reopen it if needed.
