### ISSUE TITLE
Correction for raw affiliation Dnipro State Medical University

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#5]
Correction needed for raw affiliation Dnipro State Medical University
raw_affiliation_name: Dnipro State Medical University
new_rors: 
previous_rors: 04ryqpf83
works_examples: W3165033634;W3160513373;W3161741698;W4296510867

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
