### ISSUE TITLE
Correction for raw affiliation HSEE "Dnipro State Medical University"

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#6]
Correction needed for raw affiliation HSEE "Dnipro State Medical University"
raw_affiliation_name: HSEE "Dnipro State Medical University"
new_rors: 
previous_rors: 04ryqpf83
works_examples: W3177377398;W4205937021;W4285300970;W4226193142;W4285158465

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
