### ISSUE TITLE
Correction for raw affiliation Departamento de Urología, Hotel-Dieu de France, Beirut, Líbano; Facultad de Medicina, Universidad de Saint Joseph, Beirut, Líbano

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#7]
Correction needed for raw affiliation Departamento de Urología, Hotel-Dieu de France, Beirut, Líbano; Facultad de Medicina, Universidad de Saint Joseph, Beirut, Líbano
raw_affiliation_name: Departamento de Urología, Hotel-Dieu de France, Beirut, Líbano; Facultad de Medicina, Universidad de Saint Joseph, Beirut, Líbano
new_rors: 04w1m5n60;044fxjq88
previous_rors: 03jmjy508;044fxjq88
works_examples: W3093472899

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
