### ISSUE TITLE
Correction for raw affiliation Hotel Dieu de France, Gastroenterology

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/openalex-affiliations#9]
Correction needed for raw affiliation Hotel Dieu de France, Gastroenterology
raw_affiliation_name: Hotel Dieu de France, Gastroenterology
new_rors: 04w1m5n60
previous_rors: 03jmjy508
works_examples: W3025306249

**Comment by dataesri** [comment]
This issue was accepted and ingested by the OpenAlex team on 2024-10-10. The new affiliations should be visible within the next 7 days.
